# Generated by Django 2.2.6 on 2020-11-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201101_1143'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemaster',
            name='enterprise',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='leave_master_bank_master', to='company.Enterprise', verbose_name='Enterprise Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavemaster',
            name='leave_value',
            field=models.FloatField(default=0, verbose_name='Leave Value'),
            preserve_default=False,
        ),
    ]
