# Generated by Django 2.2.6 on 2020-11-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20201104_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.LeaveMaster', verbose_name='Leave Type Name'),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='leave_value',
            field=models.FloatField(default=0, verbose_name='Leave Value'),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='type',
            field=models.CharField(max_length=200, verbose_name='Leave Type Name'),
        ),
    ]
