# Generated by Django 2.2.6 on 2021-01-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20201104_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leave_balance',
            name='carried_forward1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
