# Generated by Django 2.2.6 on 2021-01-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_employee_leave_balance_carried_forward1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_leave_balance',
            name='carried_forward1',
        ),
    ]
