# Generated by Django 2.2.6 on 2021-02-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_employee_leave_balance_carried_forward1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leave_balance',
            name='absence',
            field=models.PositiveSmallIntegerField(verbose_name='Absence'),
        ),
        migrations.AlterField(
            model_name='employee_leave_balance',
            name='carried_forward',
            field=models.PositiveSmallIntegerField(verbose_name='Carried forward'),
        ),
        migrations.AlterField(
            model_name='employee_leave_balance',
            name='casual',
            field=models.PositiveSmallIntegerField(verbose_name='Casual'),
        ),
        migrations.AlterField(
            model_name='employee_leave_balance',
            name='usual',
            field=models.PositiveSmallIntegerField(verbose_name='Usual'),
        ),
    ]
