# Generated by Django 2.2 on 2021-03-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20210301_1400'),
        ('leave', '0006_employeeabsence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='employee',
            field=models.ForeignKey(default=0.0004950495049504951, on_delete=django.db.models.deletion.CASCADE, related_name='employee_absence_employee', to='employee.Employee'),
            preserve_default=False,
        ),
    ]
