# Generated by Django 2.2 on 2021-03-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_merge_20210311_1358'),
        ('leave', '0007_employeeabsence_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvall', to='employee.Employee'),
        ),
    ]
