# Generated by Django 2.2.13 on 2021-03-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20210225_0818'),
        ('leave', '0007_employeeabsence_employee'),
    ]

    operations = [
    ]
