# Generated by Django 2.2 on 2021-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leave_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='date',
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
