# Generated by Django 2.2 on 2021-03-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20210315_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employeeabsence',
            name='start_date',
        ),
    ]
