# Generated by Django 2.2 on 2021-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20210315_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='end_date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='start_date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
