# Generated by Django 2.2.13 on 2021-04-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_merge_20210310_0856'),
        ('leave', '0011_auto_20210315_1036'),
    ]

    operations = [
    ]
