# Generated by Django 2.2.13 on 2021-01-21 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defenition', '0001_initial'),
        ('cities_light', '0008_city_timezone'),
        ('employee', '0001_initial'),
        ('company', '0002_auto_20210121_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=50, verbose_name='Assignment Name')),
                ('assignment_code', models.CharField(max_length=50, verbose_name='Assignment Code')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_batch_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150, verbose_name='Bank Name')),
                ('branch_name', models.CharField(max_length=150, verbose_name='Branch Name')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='Country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_created_by', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_bank_master', to='company.Enterprise', verbose_name='Enterprise Name')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=25, verbose_name='Payment Type Name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defenition.LookupDet', verbose_name='Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_payment_type', to='company.Enterprise', verbose_name='Enterprise Name')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll_Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=20, verbose_name='Period Name')),
                ('period_code', models.CharField(max_length=10, verbose_name='Period Code')),
                ('period_desc', models.CharField(max_length=100, verbose_name='Description')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_by', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_by', models.IntegerField(default=0)),
                ('last_update_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pay_period', models.DateField(blank=True, null=True, verbose_name='First Pay Period')),
                ('payroll_name', models.CharField(max_length=255, verbose_name='Payroll Name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_by', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_by', models.IntegerField(default=0)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_enterprise', to='company.Enterprise', verbose_name='Enterprise Name')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_payroll.Payment_Type', verbose_name='Payment Method')),
                ('period_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defenition.LookupDet', verbose_name='Period Type')),
                ('tax_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defenition.TaxRule', verbose_name='Tax Rule')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=25, verbose_name='Payment Method Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Swift Code')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_payroll.Bank_Master', verbose_name='Bank Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_payroll.Payment_Type', verbose_name='Payment Type')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Batch_Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_include_created_by', to=settings.AUTH_USER_MODEL)),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_include_dept', to='company.Department', verbose_name='Department')),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_include_emp', to='employee.Employee', verbose_name='Employee')),
                ('include_batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_include_batch', to='manage_payroll.Assignment_Batch', verbose_name='Exclude Batch Id')),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_include_job', to='company.Job', verbose_name='Job')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_include_position', to='company.Position', verbose_name='Position')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Batch_Exclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_exclude_created_by', to=settings.AUTH_USER_MODEL)),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_exclude_dept', to='company.Department', verbose_name='Department')),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_exclude_emp', to='employee.Employee', verbose_name='Employee')),
                ('exclude_batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_exclude_batch', to='manage_payroll.Assignment_Batch', verbose_name='Deduction')),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_exclude_job', to='company.Job', verbose_name='Job')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_exclude_postion', to='company.Position', verbose_name='Position')),
            ],
        ),
        migrations.AddField(
            model_name='assignment_batch',
            name='payroll_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_batch_payroll', to='manage_payroll.Payroll_Master', verbose_name='Payroll'),
        ),
    ]
