# Generated by Django 2.2.6 on 2021-01-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_master',
            name='first_pay_period',
            field=models.DateField(blank=True, null=True, verbose_name='First Pay Period'),
        ),
    ]
