# Generated by Django 2.2.6 on 2020-06-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_master',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_payroll.Payment_Type', verbose_name='Payment Method'),
        ),
    ]
