# Generated by Django 2.2.6 on 2021-01-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_payroll', '0002_auto_20210112_1713'),
        ('manage_payroll', '0002_auto_20210111_1458'),
    ]

    operations = [
    ]
