# Generated by Django 2.2.6 on 2021-01-12 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='task_start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 17, 19, 16, 970742)),
        ),
    ]
