# Generated by Django 2.2.6 on 2021-01-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_auto_20210112_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='task_start_date',
            field=models.DateField(),
        ),
    ]
