# Generated by Django 2.2.6 on 2021-01-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_merge_20201210_1341'),
        ('task_management', '0003_auto_20210112_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='company.Enterprise'),
            preserve_default=False,
        ),
    ]
