# Generated by Django 2.2.6 on 2021-01-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
