# Generated by Django 2.2.6 on 2021-01-13 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_auto_20210113_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('complete', 'Complete'), ('testing', 'Under Test'), ('closed', 'Closed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='task_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
