# Generated by Django 2.2.6 on 2021-01-14 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_auto_20210113_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_task_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
