# Generated by Django 2.2.6 on 2021-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_auto_20210114_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_task',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project_task',
            name='branch_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project_task',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
