# Generated by Django 2.2.6 on 2021-01-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_merge_20210113_1550'),
        ('task_management', '0008_auto_20210114_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_task_assignee', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='project_task',
            name='periority',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High'), ('vhigh', 'Very-High')], max_length=50, null=True),
        ),
    ]
