# Generated by Django 2.2.6 on 2021-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0009_auto_20210117_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
