# Generated by Django 2.2.6 on 2021-02-21 09:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tax Rule Name')),
                ('personal_exemption', models.FloatField(verbose_name='Personal Exemption')),
                ('round_down_to_nearest_10', models.BooleanField(default=True, verbose_name='Round To Nearest Zero')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxRule_created_by', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Enterprise', verbose_name='Enterprise Name')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxRule_last_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('salary_from', models.FloatField(verbose_name='Salary From')),
                ('salary_to', models.FloatField(default=1000000, verbose_name='Salary To')),
                ('tax_percentage', models.FloatField(verbose_name='Tax Percentage')),
                ('tax_discount_percentage', models.FloatField(verbose_name='Tax Discount Percentage')),
                ('section_execution_sequence', models.IntegerField(default=0, verbose_name='Section Execution Sequence')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxSection_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxSection_last_update_by', to=settings.AUTH_USER_MODEL)),
                ('tax_rule_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='defenition.TaxRule', verbose_name='Tax Rule Id')),
            ],
        ),
        migrations.CreateModel(
            name='Tax_Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Section Name')),
                ('salary_from', models.FloatField(verbose_name='Salary From')),
                ('salary_to', models.FloatField(default=1000000000, verbose_name='Salary To')),
                ('tax_percentage', models.FloatField(verbose_name='Tax Percentage')),
                ('tax_difference', models.FloatField(blank=True, null=True, verbose_name='Tax Difference')),
                ('section_execution_sequence', models.IntegerField(default=0, verbose_name='Section Execution Sequence')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxSections_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxSections_last_update_by', to=settings.AUTH_USER_MODEL)),
                ('tax_rule_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_sections', to='defenition.TaxRule', verbose_name='Tax Rule Id')),
            ],
        ),
        migrations.CreateModel(
            name='LookupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type_name', models.CharField(max_length=100, verbose_name='Lookup Type')),
                ('lookup_type_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookup_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_lookup_type', to='company.Enterprise', verbose_name='Enterprise Name')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_type_last_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LookupDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookup_det_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_det_last_update_by', to=settings.AUTH_USER_MODEL)),
                ('lookup_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookup_type_fk', to='defenition.LookupType', verbose_name='Lookup Type')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Insurance Rule Name')),
                ('basic_deduction_percentage', models.FloatField(verbose_name='Basic Deduction Percentage')),
                ('variable_deduction_percentage', models.FloatField(verbose_name='Variable Deduction Percentage')),
                ('maximum_insurable_basic_salary', models.FloatField(verbose_name='Maximum Insurable Basic Salary')),
                ('maximum_insurable_variable_salary', models.FloatField(verbose_name='Maximum Insurable Variable Salary')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InsuranceRule_created_by', to=settings.AUTH_USER_MODEL)),
                ('enterprise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Enterprise', verbose_name='Enterprise Name')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InsuranceRule_last_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
