# Generated by Django 2.2.6 on 2020-04-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defenition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupdet',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_det_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lookuptype',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_type_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
