# Generated by Django 2.2.6 on 2020-04-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defenition', '0003_auto_20200426_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrule',
            name='global_flag',
        ),
    ]
