# Generated by Django 2.2.6 on 2020-04-26 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defenition', '0004_remove_taxrule_global_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxRule_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxRule_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxsection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxSection_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxsection',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxSection_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
