# Generated by Django 2.2.6 on 2020-04-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200401_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobroll',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobroll',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='jobroll',
            name='job_name',
        ),
    ]
