# Generated by Django 2.2.6 on 2020-12-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0004_element_master_basic_flag'),
        ('employee', '0002_auto_20201101_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Element_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_value', models.FloatField(default=0)),
                ('salary_month', models.IntegerField(default=12)),
                ('salary_year', models.IntegerField(default=2020)),
                ('creation_date', models.DateField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='element_definition.Element_Master')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
