# Generated by Django 2.2.6 on 2020-12-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_element_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_element_history',
            name='is_done',
        ),
    ]
