# Generated by Django 2.2.6 on 2020-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200409_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=5, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('N', 'National Id'), ('P', 'Passport')], max_length=5, null=True, verbose_name='ID Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='military_status',
            field=models.CharField(blank=True, choices=[('E', 'Exemption'), ('C', 'Complete the service'), ('P', 'Postponed')], max_length=5, null=True, verbose_name='Milatery Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('C', 'Chrestin')], max_length=5, null=True, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single')], max_length=5, null=True, verbose_name='Social Status'),
        ),
    ]
