# Generated by Django 2.2.6 on 2020-12-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_element_history_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(blank=True, choices=[('UP', 'Under Probation'), ('E', 'Employee'), ('EX', 'Ex-Employee'), ('C', 'Contractor')], max_length=30, null=True, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employee_element',
            name='element_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='element_definition.Element_Master', verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='employee_element',
            name='element_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Pay Value'),
        ),
    ]
