# Generated by Django 2.2.6 on 2020-05-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200503_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_Element_Value',
        ),
    ]
