# Generated by Django 2.2.6 on 2020-12-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20201208_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_element',
            name='element_value',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pay Value'),
        ),
    ]
