# Generated by Django 2.2.6 on 2020-12-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20201206_1434'),
        ('employee', '0006_auto_20201208_1356'),
    ]

    operations = [
    ]
