# Generated by Django 2.2.6 on 2020-06-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defenition', '0005_auto_20200426_1433'),
        ('employee', '0006_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobroll',
            name='emp_type',
        ),
        migrations.AddField(
            model_name='jobroll',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobroll_contract_type', to='defenition.LookupDet', verbose_name='Contract Type'),
        ),
        migrations.AddField(
            model_name='jobroll',
            name='employee_type',
            field=models.CharField(choices=[('A', 'Admin'), ('E', 'Employee')], default='A', max_length=3, verbose_name='Employee Type'),
            preserve_default=False,
        ),
    ]
