# Generated by Django 2.2.6 on 2020-12-29 10:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0007_auto_20201229_1210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0007_merge_20201210_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_element',
            name='element_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='element_definition.Element', verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='employee_element',
            name='element_value',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pay Value'),
        ),
        migrations.CreateModel(
            name='EmployeeStructureLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_is_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_is_last_update_by', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_structure_link', to='element_definition.SalaryStructure')),
            ],
        ),
    ]
