# Generated by Django 2.2.6 on 2020-06-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20200611_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobroll',
            name='employee_type',
        ),
    ]
