# Generated by Django 2.2.6 on 2021-01-03 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0008_auto_20201229_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_element_history',
            old_name='employee',
            new_name='emp_id',
        ),
        migrations.RemoveField(
            model_name='employee_element_history',
            name='element',
        ),
        migrations.RemoveField(
            model_name='employee_element_history',
            name='salary_month',
        ),
        migrations.RemoveField(
            model_name='employee_element_history',
            name='salary_year',
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_element_history_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='element_computed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_element_history_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='employee_element',
            name='element_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pay Value'),
        ),
        migrations.AlterField(
            model_name='employee_element_history',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_element_history',
            name='element_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
