# Generated by Django 2.2.6 on 2021-01-06 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20210103_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_element_history',
            name='salary_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Salary Month'),
        ),
        migrations.AddField(
            model_name='employee_element_history',
            name='salary_year',
            field=models.IntegerField(default=2021, verbose_name='Salary Year'),
        ),
        migrations.AlterField(
            model_name='employee_element',
            name='element_value',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pay Value'),
        ),
        migrations.AlterField(
            model_name='employee_element_history',
            name='element_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
