# Generated by Django 2.2.6 on 2021-01-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201101_1143'),
        ('employee', '0010_auto_20210106_1335'),
    ]

    operations = [
    ]
