# Generated by Django 2.2.6 on 2021-02-23 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employee_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_number',
            field=models.CharField(blank=True, default='0', max_length=30, null=True, verbose_name='Employee Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='employee_element_history',
            name='salary_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=2, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Salary Month'),
        ),
    ]
