# Generated by Django 2.2 on 2021-03-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210223_0840'),
        ('employee', '0013_auto_20210223_1229'),
    ]

    operations = [
    ]
