# Generated by Django 2.2 on 2021-03-10 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20210301_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='terminationdate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Terminaton Date'),
        ),
    ]
