# Generated by Django 2.2.6 on 2021-03-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_depandance'),
        ('employee', '0014_auto_20210303_1411'),
    ]

    operations = [
    ]
