# Generated by Django 2.2.13 on 2021-03-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_terminationdate'),
        ('employee', '0016_employee_depandance'),
    ]

    operations = [
    ]
