# Generated by Django 2.2.13 on 2021-03-10 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0016_employee_depandance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_depandance',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='employee_depandance',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='employee_file',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee_file',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='employee_file',
            name='last_updated_by',
        ),
        migrations.AddField(
            model_name='employee_depandance',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee_depandance',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_depeandancy_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee_depandance',
            name='last_update_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_file',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee_file',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee_file',
            name='last_update_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_depandance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_depeandancy_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee_file',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
