# Generated by Django 2.2 on 2021-03-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_terminationdate'),
        ('employee', '0016_employee_depandance'),
    ]

    operations = [
    ]
