# Generated by Django 2.2 on 2021-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_merge_20210314_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='terminationdate',
            field=models.DateField(blank=True, null=True, verbose_name='Terminaton Date'),
        ),
    ]
