# Generated by Django 2.2.13 on 2021-04-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_terminationdate'),
        ('employee', '0017_auto_20210310_1431'),
    ]

    operations = [
    ]
