# Generated by Django 2.2.13 on 2021-03-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_merge_20210311_1358'),
        ('employee', '0017_merge_20210311_1421'),
    ]

    operations = [
    ]
