# Generated by Django 2.2 on 2021-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_merge_20210314_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='terminationdate',
            field=models.DateField(blank=True, null=True, verbose_name='Terminaton Date'),
        ),
    ]
