# Generated by Django 2.2 on 2021-03-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20210315_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='end_date',
            new_name='emp_end_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='start_date',
            new_name='emp_start_date',
        ),
    ]
