# Generated by Django 2.2.13 on 2021-03-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20210315_1606'),
        ('employee', '0019_auto_20210315_0958'),
    ]

    operations = [
    ]
