# Generated by Django 2.2.6 on 2021-03-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20210315_0958'),
        ('employee', '0017_merge_20210310_1438'),
        ('employee', '0020_auto_20210315_1606'),
    ]

    operations = [
    ]
