# Generated by Django 2.2.13 on 2021-04-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20210315_0958'),
        ('employee', '0018_merge_20210404_1154'),
        ('employee', '0020_auto_20210315_1606'),
    ]

    operations = [
    ]
