# Generated by Django 2.2.13 on 2021-04-06 09:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_merge_20210330_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_element_history',
            name='salary_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Salary Month'),
        ),
        migrations.AlterField(
            model_name='jobroll',
            name='position',
            field=models.ForeignKey(default=datetime.datetime(2021, 4, 6, 9, 13, 59, 830633, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='company.Position', verbose_name='Position'),
            preserve_default=False,
        ),
    ]
