# Generated by Django 2.2.6 on 2021-04-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_auto_20210404_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_file',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='employee_file',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='File Name'),
        ),
    ]
