# Generated by Django 2.2.6 on 2020-06-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(choices=[('A', 'Admin'), ('E', 'Employee')], default='A', max_length=3, verbose_name='Employee Type'),
            preserve_default=False,
        ),
    ]
