# Generated by Django 2.2.6 on 2021-03-03 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_merge_20210113_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_name', models.CharField(max_length=100, verbose_name='Performance Name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Enterprise')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Department')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Job')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Position')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Performance')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('help_text', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.PerformanceTitle')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_key', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')])),
                ('score_value', models.CharField(blank=True, max_length=255, null=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Performance')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('Over all', 'Over all'), ('Core', 'Core'), ('Job', 'Job')], max_length=25)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Performance')),
            ],
        ),
    ]
