# Generated by Django 2.2.6 on 2021-03-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20210310_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='rating',
            field=models.CharField(max_length=255),
        ),
    ]
