# Generated by Django 2.2.6 on 2021-03-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20210311_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='performance.Segment'),
        ),
    ]
