# Generated by Django 2.2.6 on 2021-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_auto_20210316_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('slider', 'slider')], default='slider', max_length=25),
        ),
    ]
