# Generated by Django 2.2.6 on 2021-03-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
