# Generated by Django 2.2.6 on 2021-03-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_auto_20210317_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerating',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='performance.Performance'),
        ),
    ]
