# Generated by Django 2.2.6 on 2021-04-01 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0022_auto_20210401_1204'),
        ('performance', '0012_auto_20210317_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='performance_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Performance Name'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='performance.Performance'),
        ),
        migrations.CreateModel(
            name='EmployeeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeRating_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeRating_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Question')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.PerformanceRating')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('core_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core', to='performance.PerformanceRating')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeePerformance_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('job_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='performance.PerformanceRating')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeePerformance_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('overall_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall', to='performance.PerformanceRating')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Performance')),
            ],
        ),
    ]
