# Generated by Django 2.2.13 on 2021-02-07 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('balanc_definition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_level',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_level_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost_level',
            name='last_update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_level_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost_detail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_detail_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost_detail',
            name='last_update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_detail_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost_detail',
            name='level_Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='cost_detail',
            name='level_Grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Grade', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='cost_detail',
            name='level_Job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='cost_detail',
            name='level_Position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='cost_detail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanc_definition.Cost_Level', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='cost_center_link',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balanc_definition.Cost_Center', verbose_name='Element Name'),
        ),
        migrations.AddField(
            model_name='cost_center_link',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_center_link_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost_center_link',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='Department'),
        ),
    ]
