# Generated by Django 2.2.13 on 2021-03-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanc_definition', '0004_auto_20210207_1023'),
        ('balanc_definition', '0004_auto_20210111_0859'),
    ]

    operations = [
    ]
