# Generated by Django 2.2.6 on 2020-07-26 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('company', '0002_auto_20200726_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_purchase', models.DateField(default=datetime.date.today, verbose_name='Date Of Purchase')),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('C', 'Cash'), ('V', 'Visa')], max_length=2, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('vendor_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=12, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Department')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, max_length=250, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=250, null=True)),
                ('unit_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('qnt', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item_updated_by', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Purchase_Request')),
            ],
        ),
        migrations.CreateModel(
            name='Bussiness_Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now_add=True, verbose_name='Date Requested')),
                ('destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination')),
                ('estimated_date_of_travel_from', models.DateField(verbose_name='From Date')),
                ('estimated_date_of_travel_to', models.DateField(verbose_name='To Date')),
                ('prupose_of_trip', models.CharField(blank=True, max_length=250, null=True, verbose_name='Prupose Of Trip')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Name')),
                ('transportation_type_to_des', models.CharField(choices=[('P', 'Plane'), ('T', 'Train'), ('B', 'Bus'), ('C', 'Personal Car')], max_length=1, verbose_name='Transportation Type')),
                ('ticket_cost', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ticket Cost')),
                ('fuel_cost', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Fuel Cost')),
                ('transportation_type_in_city', models.CharField(blank=True, choices=[('U', 'Uber'), ('C', 'Car Rental'), ('F', 'Ferry'), ('O', 'Others')], max_length=1, null=True)),
                ('cost', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('accomodation', models.CharField(blank=True, choices=[('C', 'Company Accomodation'), ('H', 'Hotel Accomodation')], max_length=20, null=True, verbose_name='Accomodation')),
                ('duration_of_hotel_from', models.DateField(blank=True, null=True)),
                ('duration_of_hotel_to', models.DateField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_per_night', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_department', to='company.Department', verbose_name='Department')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_employee', to='employee.Employee', verbose_name='Employee Name')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_manager', to='employee.Employee', verbose_name='Manager Name')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_department', to='company.Position', verbose_name='Position')),
            ],
        ),
    ]
