# Generated by Django 2.2.6 on 2020-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness_travel',
            name='transportation_type_in_city',
            field=models.CharField(blank=True, choices=[('U', 'Uber'), ('C', 'Car Rental'), ('F', 'Ferry'), ('O', 'Others')], max_length=1, null=True),
        ),
    ]
