# Generated by Django 2.2.6 on 2020-11-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness_travel',
            name='is_approved',
        ),
    ]
