# Generated by Django 2.2.6 on 2020-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_bussiness_travel_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness_travel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
