# Generated by Django 2.2.6 on 2021-03-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_bussiness_travel_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='qnt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='unit_price',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='vendor_name',
            field=models.CharField(max_length=250),
            preserve_default=False,
        ),
    ]
