# Generated by Django 2.2 on 2021-03-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_bussiness_travel_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='item_description',
            field=models.CharField(default=0.0004950495049504951, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='qnt',
            field=models.PositiveIntegerField(default=0.0004950495049504951),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='unit_price',
            field=models.PositiveIntegerField(default=0.0004950495049504951),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='vendor_name',
            field=models.CharField(default=0.0004950495049504951, max_length=250),
            preserve_default=False,
        ),
    ]
