# Generated by Django 2.2.6 on 2021-03-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210308_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='item_description',
            field=models.CharField(default='handel error', max_length=250),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='qnt',
            field=models.PositiveIntegerField(default='handel error'),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='unit_price',
            field=models.PositiveIntegerField(default='handel error'),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='vendor_name',
            field=models.CharField(default='handel error', max_length=250),
        ),
    ]
