# Generated by Django 2.2.6 on 2021-03-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210308_0927'),
        ('service', '0004_auto_20210308_0913'),
    ]

    operations = [
    ]
