# Generated by Django 2.2 on 2021-03-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210308_0927'),
    ]

    operations = [
    ]
