# Generated by Django 2.2.13 on 2021-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210308_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='item_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='qnt',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='vendor_name',
            field=models.CharField(max_length=250),
        ),
    ]
