# Generated by Django 2.2.13 on 2021-04-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_merge_20210310_1419'),
        ('service', '0007_purchase_item_unit_price_null_true'),
    ]

    operations = [
    ]
