# Generated by Django 2.2.6 on 2021-03-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_merge_20210310_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='item_description',
            field=models.CharField(default='handel error', max_length=250),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='qnt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='unit_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='vendor_name',
            field=models.CharField(default='handel error', max_length=250),
        ),
    ]
