# Generated by Django 2.2.13 on 2021-03-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_purchase_request_emp'),
        ('service', '0007_purchase_item_unit_price_null_true'),
    ]

    operations = [
    ]
