# Generated by Django 2.2.6 on 2021-03-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_merge_20210314_0812'),
        ('service', '0008_auto_20210310_1438'),
    ]

    operations = [
    ]
