# Generated by Django 2.2.13 on 2021-04-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_merge_20210404_1154'),
        ('service', '0010_merge_20210314_0812'),
    ]

    operations = [
    ]
