# Generated by Django 2.2.6 on 2021-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_merge_20210316_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='item_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='qnt',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='vendor_name',
            field=models.CharField(max_length=250),
        ),
    ]
