# Generated by Django 2.2.6 on 2020-09-03 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200903_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
