# Generated by Django 2.2.6 on 2020-04-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200401_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='commercail_record',
            field=models.CharField(max_length=150, verbose_name='Commercial Record'),
        ),
    ]
