# Generated by Django 2.2.6 on 2020-05-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200420_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='business_unit_name',
        ),
    ]
