# Generated by Django 2.2.6 on 2020-12-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201206_1256'),
        ('company', '0003_auto_20201208_1329'),
    ]

    operations = [
    ]
