# Generated by Django 2.2.6 on 2021-01-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_merge_20201210_1341'),
        ('company', '0002_auto_20210111_0859'),
    ]

    operations = [
    ]
