# Generated by Django 2.2.6 on 2020-06-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_enterprise_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise_policies',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='policy_enterprise', to='company.Enterprise', verbose_name='Enterprise Name'),
            preserve_default=False,
        ),
    ]
