# Generated by Django 2.2.6 on 2020-06-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_enterprise_policies_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_user',
        ),
    ]
