# Generated by Django 2.2.13 on 2021-03-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210207_1023'),
        ('company', '0006_auto_20210225_0818'),
    ]

    operations = [
    ]
