# Generated by Django 2.2.6 on 2020-06-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_position_position_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='slug',
            field=models.SlugField(default='123'),
            preserve_default=False,
        ),
    ]
