# Generated by Django 2.2.6 on 2020-06-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_enterprise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
