# Generated by Django 2.2.6 on 2020-04-01 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('element_definition', '0001_initial'),
        ('defenition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element_link',
            name='payroll_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_payroll.Payroll_Master', verbose_name='Payroll'),
        ),
        migrations.AddField(
            model_name='element_detail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_det_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='element_detail',
            name='element_detail_master_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_detail_master_fk', to='element_definition.Element_Master', verbose_name='Element'),
        ),
        migrations.AddField(
            model_name='element_detail',
            name='last_update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_det_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='element_detail',
            name='parameter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_input_type', to='defenition.LookupDet', verbose_name='Parameter Type'),
        ),
        migrations.AddField(
            model_name='element_batch_master',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='element_batch_master',
            name='element_batch_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_batch_fk', related_query_name='elementBatch', to='element_definition.Element_Batch', verbose_name='Element Batch'),
        ),
        migrations.AddField(
            model_name='element_batch_master',
            name='element_master_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_master_fk', related_query_name='elementMaster', to='element_definition.Element_Master', verbose_name='Element'),
        ),
        migrations.AddField(
            model_name='element_batch_master',
            name='last_update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='element_batch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_batch_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='element_batch',
            name='last_update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_batch_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='element_batch',
            name='payroll_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_payroll.Payroll_Master', verbose_name='Payroll'),
        ),
        migrations.AddField(
            model_name='custom_python_rule',
            name='element_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_python_rule', to='element_definition.Element_Master', verbose_name='Element Master'),
        ),
    ]
