# Generated by Django 2.2.6 on 2020-07-26 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('element_definition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element_link',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='element_link',
            name='last_update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_link_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
