# Generated by Django 2.2.6 on 2020-04-27 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0002_auto_20200401_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element_master',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_master_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
