# Generated by Django 2.2.6 on 2020-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0003_auto_20201101_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='element_master',
            name='basic_flag',
            field=models.BooleanField(default=False),
        ),
    ]
