# Generated by Django 2.2.6 on 2020-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0003_auto_20200427_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element_master',
            name='global_value',
        ),
        migrations.AddField(
            model_name='element_master',
            name='fixed_amount',
            field=models.IntegerField(default=0, verbose_name='Fixed Amount'),
        ),
    ]
