# Generated by Django 2.2.6 on 2020-06-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_delete_employee_element_value'),
        ('element_definition', '0004_auto_20200427_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element_link',
            name='assignment_category',
        ),
        migrations.AddField(
            model_name='element_link',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='element_definition.Element_Batch', verbose_name='Batch Name'),
        ),
        migrations.AddField(
            model_name='element_link',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee Name'),
        ),
    ]
