# Generated by Django 2.2.6 on 2020-12-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0004_element_master_basic_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_python_rule',
            name='element_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_python_rule', to='element_definition.Element_Master', verbose_name='Pay Master'),
        ),
        migrations.AlterField(
            model_name='element_batch_master',
            name='element_batch_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_batch_fk', related_query_name='elementBatch', to='element_definition.Element_Batch', verbose_name='Pay Batch'),
        ),
        migrations.AlterField(
            model_name='element_batch_master',
            name='element_master_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_master_fk', related_query_name='elementMaster', to='element_definition.Element_Master', verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='element_detail',
            name='element_detail_master_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_detail_master_fk', to='element_definition.Element_Master', verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='element_link',
            name='element_master_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_link_to_master', to='element_definition.Element_Master', verbose_name='Pay Name'),
        ),
        migrations.AlterField(
            model_name='element_master',
            name='element_name',
            field=models.CharField(max_length=100, verbose_name='Pay Name'),
        ),
        migrations.AlterField(
            model_name='element_master',
            name='element_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_element', to='defenition.LookupDet', verbose_name='Pay Type'),
        ),
    ]
