# Generated by Django 2.2.6 on 2020-12-29 10:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_merge_20201210_1341'),
        ('defenition', '0001_initial'),
        ('element_definition', '0006_merge_20201210_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100, verbose_name='Pay Name')),
                ('code', models.CharField(blank=True, max_length=4, null=True, verbose_name='code')),
                ('element_type', models.CharField(choices=[('payslip based', 'payslip based'), ('global value', 'global value'), ('formula', 'formula')], max_length=100)),
                ('amount_type', models.CharField(choices=[('fixed amount', 'fixed amount'), ('percentage', 'percentage'), ('days', 'days'), ('hrs', 'hrs'), ('months', 'months')], max_length=100)),
                ('fixed_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount')),
                ('element_formula', models.TextField(blank=True, max_length=255, null=True, verbose_name='Formula')),
                ('appears_on_payslip', models.BooleanField(default=True, verbose_name='Appears on payslip')),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('tax_flag', models.BooleanField(default=False, verbose_name='Tax Flag')),
                ('scheduled_pay', models.CharField(choices=[('yearly', 'yearly'), ('monthly', 'monthly'), ('weekly', 'weekly')], max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='element_definition.Element')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_lookup_classification', to='defenition.LookupDet', verbose_name='classification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_is_created_by', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_salary_elements', to='company.Enterprise', verbose_name='Enterprise Name')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_is_last_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_name', models.CharField(max_length=255, verbose_name='Structure Name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure_created_by', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_salary_structures', to='company.Enterprise', verbose_name='Enterprise Name')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure_last_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StructureElementLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_is_created_by', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_link', to='element_definition.Element')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_is_last_update_by', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_link', to='element_definition.SalaryStructure')),
            ],
        ),
        migrations.DeleteModel(
            name='Element_Detail',
        ),
    ]
