# Generated by Django 2.2.6 on 2021-01-03 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_merge_20201210_1341'),
        ('defenition', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('element_definition', '0007_auto_20201229_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_lookup_classification', to='defenition.LookupDet', verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='element',
            name='amount_type',
            field=models.CharField(blank=True, choices=[('fixed amount', 'Amount'), ('percentage', 'Percentage'), ('days', 'Days'), ('hrs', 'Hrs'), ('months', 'Months')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('payslip based', 'Payslip based'), ('global value', 'Global value'), ('formula', 'Formula')], max_length=100),
        ),
        migrations.AlterField(
            model_name='element',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='element',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_is_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='element',
            name='scheduled_pay',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structureelementlink',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_is_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ElementHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pay Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='code')),
                ('element_type', models.CharField(blank=True, choices=[('payslip based', 'Payslip based'), ('global value', 'Global value'), ('formula', 'Formula')], max_length=100, null=True)),
                ('amount_type', models.CharField(blank=True, choices=[('fixed amount', 'Amount'), ('percentage', 'Percentage'), ('days', 'Days'), ('hrs', 'Hrs'), ('months', 'Months')], max_length=100, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('element_formula', models.TextField(blank=True, max_length=255, null=True, verbose_name='Formula')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('appears_on_payslip', models.BooleanField(blank=True, default=True, null=True, verbose_name='Appears on payslip')),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('tax_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Tax Flag')),
                ('scheduled_pay', models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='defenition.LookupDet', verbose_name='classification')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_history_is_created_by', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_salary_elements_history', to='company.Enterprise', verbose_name='Enterprise Name')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_history_is_last_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
