# Generated by Django 2.2.6 on 2021-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0008_auto_20210103_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='db_name',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='db Name'),
        ),
    ]
