# Generated by Django 2.2.6 on 2021-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0009_element_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element_master',
            name='db_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='db Name'),
        ),
    ]
