# Generated by Django 2.2.6 on 2021-01-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0010_auto_20210112_1713'),
        ('element_definition', '0010_auto_20210111_1039'),
    ]

    operations = [
    ]
