# Generated by Django 2.2.6 on 2021-01-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0003_auto_20210111_0859'),
        ('element_definition', '0010_auto_20210112_1713'),
    ]

    operations = [
    ]
