# Generated by Django 2.2.6 on 2021-01-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0011_merge_20210114_1104'),
        ('element_definition', '0011_merge_20210113_1550'),
    ]

    operations = [
    ]
