# Generated by Django 2.2 on 2021-03-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0012_merge_20210117_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='structure_type',
            field=models.CharField(choices=[('Net to Gross', 'Net to Gross'), ('Gross to Net', 'Gross to Net')], default=0.0004950495049504951, max_length=100),
            preserve_default=False,
        ),
    ]
