# Generated by Django 2.2.6 on 2021-02-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0012_merge_20210117_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='db_name',
        ),
        migrations.AlterField(
            model_name='element',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_lookup_classification', to='defenition.LookupDet', verbose_name='classification'),
        ),
    ]
