# Generated by Django 2.2 on 2021-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0013_salarystructure_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='Is basic'),
        ),
    ]
