# Generated by Django 2.2.6 on 2021-03-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0013_auto_20210225_0818'),
        ('element_definition', '0013_salarystructure_structure_type'),
    ]

    operations = [
    ]
