# Generated by Django 2.2.6 on 2021-03-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0013_salarystructure_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='Is basic'),
        ),
        migrations.CreateModel(
            name='ElementFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=20, max_digits=200, null=True)),
                ('arithmetic_signs', models.CharField(blank=True, choices=[('%', '%'), ('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], max_length=100, null=True)),
                ('arithmetic_signs_additional', models.CharField(blank=True, choices=[('%', '%'), ('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], max_length=100, null=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_based_on', to='element_definition.Element')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_id', to='element_definition.Element')),
            ],
        ),
    ]
