# Generated by Django 2.2 on 2021-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0013_salarystructure_structure_type'),
    ]

    operations = [    ]
