# Generated by Django 2.2.13 on 2021-03-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0003_auto_20210207_1023'),
        ('element_definition', '0014_merge_20210308_1307'),
    ]

    operations = [
    ]
