# Generated by Django 2.2.6 on 2021-03-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0014_auto_20210315_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementformula',
            name='arithmetic_signs_additional',
        ),
    ]
