# Generated by Django 2.2.6 on 2021-03-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0015_remove_elementformula_arithmetic_signs_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementformula',
            name='arithmetic_signs_additional',
            field=models.CharField(blank=True, choices=[('%', '%'), ('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], max_length=100, null=True),
        ),
    ]
