# Generated by Django 2.2.6 on 2021-03-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0016_elementformula_arithmetic_signs_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementformula',
            name='based_on',
        ),
    ]
