# Generated by Django 2.2.6 on 2021-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0018_elementformula_based_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='Is basic'),
        ),
    ]
