# Generated by Django 2.2.13 on 2021-04-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0014_element_is_basic'),
        ('element_definition', '0015_merge_20210310_0858'),
        ('element_definition', '0018_elementformula_based_on'),
    ]

    operations = [
    ]
