# Generated by Django 2.2.13 on 2021-03-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0018_elementformula_based_on'),
        ('element_definition', '0014_element_is_basic'),
    ]

    operations = [
    ]
