# Generated by Django 2.2.6 on 2021-03-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0014_element_is_basic'),
    ]

    operations = [
    ]
