# Generated by Django 2.2.6 on 2021-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0020_merge_20210316_1455'),
    ]

    
