# Generated by Django 2.2.6 on 2021-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0020_auto_20210404_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='Is basic'),
        ),
    ]
