# Generated by Django 2.2.6 on 2021-03-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0021_auto_20210317_0807'),
    ]

    operations = [
    ]
