# Generated by Django 2.2.6 on 2021-03-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0022_merge_20210317_0811'),
        ('element_definition', '0018_elementformula_based_on'),
    ]

    operations = [
    ]
