# Generated by Django 2.2.6 on 2020-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_elements',
            name='delays',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Delays'),
        ),
        migrations.AddField(
            model_name='salary_elements',
            name='penalties',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Penalties'),
        ),
    ]
