# Generated by Django 2.2.6 on 2020-12-02 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0002_auto_20201126_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_elements',
            name='last_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_last_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
