# Generated by Django 2.2.6 on 2021-01-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0003_auto_20201202_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_elements',
            name='num_days',
        ),
    ]
