# Generated by Django 2.2.6 on 2021-01-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element_definition', '0012_merge_20210117_1523'),
        ('payroll_run', '0004_remove_salary_elements_num_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_elements',
            name='element_batch',
        ),
        migrations.AddField(
            model_name='salary_elements',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='element_definition.Element', verbose_name='Element'),
        ),
        migrations.AddField(
            model_name='salary_elements',
            name='elements_type_to_run',
            field=models.CharField(choices=[('appear', 'Appear on Payslip'), ('no_appear', 'Do not Appear on Payslip')], default='appear', max_length=50, verbose_name='Run on Elements'),
        ),
    ]
