# Generated by Django 2.2.6 on 2021-01-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0005_auto_20210126_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_elements',
            name='elements_type_to_run',
            field=models.CharField(choices=[('appear', 'Appear on Payslip'), ('no_appear', 'Do not Appear on Payslip')], default='appear', max_length=50, verbose_name='Run on Elements that'),
        ),
    ]
