# Generated by Django 2.2.6 on 2021-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0007_auto_20210127_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_elements',
            name='elements_type_to_run',
            field=models.CharField(choices=[('appear', 'Payslip elements'), ('no_appear', 'Not payslip elements')], default='appear', max_length=50, verbose_name='Run on'),
        ),
    ]
