# Generated by Django 2.2 on 2021-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0008_auto_20210127_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('start_range', models.IntegerField()),
                ('end_range', models.IntegerField()),
                ('diffrence', models.IntegerField()),
                ('tax', models.IntegerField()),
            ],
        ),
    ]
