# Generated by Django 2.2 on 2021-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0009_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='diffrence',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='diffrence'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='end_range',
            field=models.IntegerField(default=0.0, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='percent',
            field=models.FloatField(default=0.0, verbose_name='percent'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='start_range',
            field=models.IntegerField(default=0.0, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='tax',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='tax'),
        ),
    ]
