# Generated by Django 2.2.6 on 2021-03-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0009_auto_20210225_0818'),
        ('payroll_run', '0010_auto_20210301_1435'),
    ]

    operations = [
    ]
