# Generated by Django 2.2.13 on 2021-03-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_run', '0011_merge_20210308_1308'),
        ('payroll_run', '0011_merge_20210302_1452'),
    ]

    operations = [
    ]
