# Generated by Django 2.2.6 on 2020-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
