# Generated by Django 2.2.6 on 2020-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='work_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
