# Generated by Django 2.2.6 on 2020-06-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200614_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='work_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
