# Generated by Django 2.2.6 on 2020-11-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20201101_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_interface',
            old_name='employee',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='attendance_interface',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance_interface',
            name='check_out',
        ),
        migrations.AddField(
            model_name='attendance_interface',
            name='user_name',
            field=models.CharField(default='aaa', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance_interface',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
