# Generated by Django 2.2.6 on 2020-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200726_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
