# Generated by Django 2.2.6 on 2020-11-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201101_1143'),
        ('attendance', '0004_auto_20201110_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_interface',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='company.Enterprise'),
            preserve_default=False,
        ),
    ]
