# Generated by Django 2.2.6 on 2020-11-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_interface_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_interface',
            name='punch',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
