# Generated by Django 2.2.6 on 2020-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_interface_punch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
