# Generated by Django 2.2.6 on 2021-01-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='task_management.Project_Task'),
        ),
    ]
