# Generated by Django 2.2.6 on 2021-01-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210111_0859'),
        ('attendance', '0008_auto_20210113_1128'),
    ]

    operations = [
    ]
