# Generated by Django 2.2.6 on 2020-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='delay_hrs',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='exceptional_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='exceptional_overtime',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='normal_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='normal_overtime',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
