# Generated by Django 2.2.6 on 2020-08-26 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0009_employee_insurance_salary'),
        ('attendance', '0010_auto_20200826_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Attendance_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('year', models.DateField()),
                ('attendance_days', models.PositiveIntegerField(blank=True, null=True)),
                ('leave_days', models.PositiveIntegerField(blank=True, null=True)),
                ('absence_days', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_history_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_history_employee', to='employee.Employee')),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_history_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
