# Generated by Django 2.2.6 on 2020-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_employee_attendance_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
