# Generated by Django 2.2.6 on 2020-08-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20200827_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
