# Generated by Django 2.2.6 on 2020-08-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20200827_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='absence_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='attendance_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='leave_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_attendance_history',
            name='year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
