# Generated by Django 2.2.6 on 2020-08-31 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0014_auto_20200827_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='normal_overtime',
            new_name='normal_overtime_hours',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='work_time',
            new_name='work_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='day_of_week',
            field=models.CharField(default='MONDAY', max_length=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Attendance_Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_interface_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_interface_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
